name: client_ao
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  equatable: ^2.0.5
  hive: ^2.2.3
  uuid: ^4.5.1
  davi: ^3.5.0
  web_socket_channel: ^3.0.1
  multi_split_view: ^3.5.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  xml: ^6.5.0
  flutter_highlighter: ^0.1.1
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  jinja: ^0.6.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:

  uses-material-design: true

  assets:
    - src/svg/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700