name: client_ao
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  equatable: ^2.0.5
  hive: ^2.2.3
  uuid: ^3.0.7
  davi: ^3.2.0
  web_socket_channel: ^2.4.0
  multi_split_view: ^2.4.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.2
  xml: ^5.4.1
  flutter_highlighter: ^0.1.1
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0
  jinja: ^0.4.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - src/svg/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700